#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@interface RCT_EXTERN_MODULE(LiteLLMNativeLeaf, RCTEventEmitter)
RCT_EXTERN_METHOD(openWindow:(NSString *)route)
RCT_EXTERN_METHOD(closeWindow:(NSString *)route)
RCT_EXTERN_METHOD(focusWindow:(NSString *)route)
RCT_EXTERN_METHOD(setWindowContentSize:(NSString *)route width:(nonnull NSNumber *)width height:(nonnull NSNumber *)height resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(setMenuBarStatus:(NSString *)title running:(BOOL)running)
RCT_EXTERN_METHOD(setMenuBarActions:(NSArray *)actions)
RCT_EXTERN_METHOD(setTrayStatus:(NSString *)title running:(BOOL)running)
RCT_EXTERN_METHOD(setTrayActions:(NSArray *)actions)
RCT_EXTERN_METHOD(openFilePicker:(NSString *)purpose resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(saveFilePicker:(NSString *)suggestedName resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(showConfirmation:(NSString *)title message:(NSString *)message confirmLabel:(NSString *)confirmLabel resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(showGroupManager:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(updateGroupManager:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(showCodexRestartConfirmation:(NSString *)title message:(NSString *)message restartLabel:(NSString *)restartLabel laterLabel:(NSString *)laterLabel resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(showReadOnlyText:(NSString *)title text:(NSString *)text closeLabel:(NSString *)closeLabel language:(NSString *)language html:(NSString *)html resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(showProviderAuth:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(showActionMenu:(NSString *)title items:(NSArray *)items anchor:(NSDictionary *)anchor resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(showGroupedActionMenu:(NSString *)title groups:(NSArray *)groups anchor:(NSDictionary *)anchor resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(chooseModelsToAdd:(NSArray *)models providerName:(NSString *)providerName keyName:(NSString *)keyName resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(setShortcuts:(NSDictionary *)shortcuts)
RCT_EXTERN_METHOD(setLocalization:(NSDictionary *)strings)
RCT_EXTERN_METHOD(editSecret:(NSString *)domain field:(NSString *)field target:(NSString *)target title:(NSString *)title allowClear:(BOOL)allowClear resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(clearSecret:(NSString *)domain field:(NSString *)field target:(NSString *)target resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(copySecret:(NSString *)domain field:(NSString *)field target:(NSString *)target resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(relayLogin:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(cancelRelayLogin)
RCT_EXTERN_METHOD(openRelayLogs:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(restoreRelaySession:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(clearRelayPassword:(NSString *)accountID resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(clearRelayCredentials:(NSString *)accountID resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN__BLOCKING_SYNCHRONOUS_METHOD(systemLocale)
RCT_EXTERN_METHOD(setLaunchAtLogin:(BOOL)enabled resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(restartCodex:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(showVersion)
RCT_EXTERN_METHOD(versionInfo:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(openExternalURL:(NSString *)url)
RCT_EXTERN_METHOD(revealFile:(NSString *)path)
RCT_EXTERN_METHOD(openFileEditor:(NSString *)payload)
RCT_EXTERN_METHOD(prepareFileEditor)
RCT_EXTERN__BLOCKING_SYNCHRONOUS_METHOD(pendingFileEditorTarget)
RCT_EXTERN_METHOD(quit)
@end
#endif
