"""Runtime Settings schema and validation shared by the configuration package."""

from __future__ import annotations

import base64
import binascii
import json
import math
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
import re

from young_router.core.runtime_settings_schema import runtime_settings_metadata
from young_router.json_input import duplicate_key_hook, read_limited_utf8


MAX_PACKAGE_BYTES = 16 * 1024 * 1024
MAX_JSON_SETTING_BYTES = 256 * 1024
RUNTIME_SETTINGS_HEADER = "# Young Router runtime thresholds. Generated by Python Core."
RETAIN_EXISTING_VALUE = "__YOUNG_ROUTER_RETAIN_EXISTING__"
RETIRED_PERSISTED_SETTINGS = frozenset(
    {
        "LITELLM_CONFIG_WATCH_INTERVAL",
        "LITELLM_CONFIG_WATCH_SETTLE_INTERVAL",
        # Legacy shell-service controls with no reader in the Python Core.
        "LITELLM_MAX_REQUESTS_BEFORE_RESTART",
        "LITELLM_STATE_TTL_SECONDS",
        "LITELLM_RUNTIME_VERIFY_WAIT_SECONDS",
        "LITELLM_SERVICE_LIFECYCLE_LOCK_WAIT_SECONDS",
        "YOUNG_ROUTER_RELAY_AUTO_GROUP_INTERVAL_MINUTES",
        # The computer-use facade had no executor the router could drive itself.
        "YOUNG_ROUTER_COMPUTER_FACADE_BACKEND",
        "YOUNG_ROUTER_COMPUTER_FACADE_MODEL",
        "YOUNG_ROUTER_COMPUTER_FACADE_MAX_STEPS",
        "YOUNG_ROUTER_COMPUTER_FACADE_TRACE",
        "YOUNG_ROUTER_COMPUTER_FACADE_TRACE_SCREENSHOTS",
        "YOUNG_ROUTER_COMPUTER_FACADE_ACTION_DENYLIST",
        "YOUNG_ROUTER_COMPUTER_FACADE_REQUIRE_OBSERVATION",
        "YOUNG_ROUTER_VISION_BRIDGE_BACKEND",
        "YOUNG_ROUTER_VISION_BRIDGE_API_BASE",
        "YOUNG_ROUTER_VISION_BRIDGE_API_KEY",
        "YOUNG_ROUTER_VISION_BRIDGE_MODEL",
        "YOUNG_ROUTER_VISION_BRIDGE_TIMEOUT_SECONDS",
        "YOUNG_ROUTER_VISION_BRIDGE_PROMPT",
        "YOUNG_ROUTER_VISION_BRIDGE_LOCAL_FORMAT",
    }
)


class PackageError(ValueError):
    """A package or source settings file is not safe to use."""


@dataclass(frozen=True)
class RuntimeSettingSpec:
    key: str
    kind: str
    default: str
    minimum: float | int | None
    maximum: float | int | None
    options: tuple[str, ...]


def load_specs() -> dict[str, RuntimeSettingSpec]:
    """Build the validation schema from bundled Core-owned Python data."""

    specs: dict[str, RuntimeSettingSpec] = {}
    for item in runtime_settings_metadata():
        if not isinstance(item, dict):
            raise PackageError("Runtime Settings schema is unavailable.")
        key = item.get("key")
        if not isinstance(key, str) or key in specs:
            raise PackageError("Runtime Settings schema is unavailable.")
        kind = item.get("kind")
        default = item.get("default")
        minimum = item.get("minimum")
        maximum = item.get("maximum")
        if (
            not isinstance(kind, str)
            or not isinstance(default, str)
        ):
            raise PackageError("Runtime Settings schema is unavailable.")
        options = item.get("options", [])
        if not isinstance(options, list) or not all(isinstance(option, str) for option in options):
            raise PackageError("Runtime Settings schema is unavailable.")
        specs[key] = RuntimeSettingSpec(
            key=key,
            kind=kind,
            default=default,
            minimum=minimum,
            maximum=maximum,
            options=tuple(options),
        )
    return specs


def _number_text(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".")


def _normalize_number(spec: RuntimeSettingSpec, raw: str) -> str:
    text = raw.strip()
    if spec.kind.startswith("optional_") and not text:
        return ""
    text = text or spec.default
    number_kind = spec.kind.removeprefix("optional_")
    if number_kind == "int":
        if not re.fullmatch(r"\d+", text):
            raise PackageError(f"{spec.key} must be an integer.")
        numeric: float | int = int(text)
        normalized = str(numeric)
    elif number_kind == "mb":
        if not re.fullmatch(r"\d+(?:\.\d+)?", text):
            raise PackageError(f"{spec.key} must be a number of MB.")
        numeric = float(text)
        if not math.isfinite(numeric):
            raise PackageError(f"{spec.key} must be finite.")
        normalized = _number_text(numeric)
    else:
        if not re.fullmatch(r"\d+(?:\.\d+)?", text):
            raise PackageError(f"{spec.key} must be a number.")
        numeric = float(text)
        if not math.isfinite(numeric):
            raise PackageError(f"{spec.key} must be finite.")
        normalized = _number_text(numeric)
    if spec.minimum is not None and numeric < spec.minimum:
        raise PackageError(f"{spec.key} must be at least {spec.minimum}.")
    if spec.maximum is not None and numeric > spec.maximum:
        raise PackageError(f"{spec.key} must be at most {spec.maximum}.")
    return normalized


def _reject_json_constant(value: str) -> object:
    raise ValueError(f"non-finite JSON constant {value} is not allowed")


_reject_duplicate_json_keys = duplicate_key_hook(
    lambda key: ValueError(f"duplicate JSON key: {key}")
)


def _parse_json_object(text: str) -> dict[str, object]:
    try:
        parsed = json.loads(
            text,
            object_pairs_hook=_reject_duplicate_json_keys,
            parse_constant=_reject_json_constant,
        )
    except (TypeError, ValueError) as exc:
        raise PackageError("JSON must be valid, finite, and free of duplicate keys.") from exc
    if not isinstance(parsed, dict):
        raise PackageError("JSON must contain an object.")
    return parsed


def normalize_payload_value(spec: RuntimeSettingSpec, raw: object) -> str:
    """Normalize a value exactly as the Runtime Settings save payload expects."""

    if not isinstance(raw, str):
        raise PackageError(f"{spec.key} must be a string.")
    if raw == RETAIN_EXISTING_VALUE:
        raise PackageError(f"{spec.key} cannot use the retain-existing marker in a package.")
    if spec.kind in {"int", "float", "mb", "optional_int", "optional_float", "optional_mb"}:
        return _normalize_number(spec, raw)
    if spec.kind == "json":
        text = raw.strip() or spec.default
        if len(text.encode("utf-8")) > MAX_JSON_SETTING_BYTES:
            raise PackageError(f"{spec.key} is too large.")
        try:
            parsed = _parse_json_object(text)
        except PackageError as exc:
            raise PackageError(f"{spec.key} must contain valid JSON.") from exc
        canonical = json.dumps(parsed, ensure_ascii=False, separators=(",", ":"), allow_nan=False)
        try:
            canonical.encode("utf-8")
        except UnicodeEncodeError as exc:
            raise PackageError(f"{spec.key} must contain valid UTF-8 JSON.") from exc
        return canonical
    if spec.kind == "string" and any(character in raw for character in "\n\r#"):
        raise PackageError(f"{spec.key} cannot contain newlines or #.")
    text = raw.strip() or spec.default
    if spec.kind == "bool":
        lowered = text.lower()
        if lowered in {"1", "true", "yes", "on"}:
            return "1"
        if lowered in {"0", "false", "no", "off"}:
            return "0"
        raise PackageError(f"{spec.key} must be a boolean.")
    if spec.kind == "bool_auto":
        lowered = text.lower()
        if lowered in {"1", "true", "yes", "on", "auto", "enabled"}:
            return "auto"
        if lowered in {"0", "false", "no", "off", "disabled"}:
            return "off"
        raise PackageError(f"{spec.key} must be a boolean.")
    if spec.kind == "enum":
        lowered = text.lower()
        if lowered not in spec.options:
            raise PackageError(f"{spec.key} must be one of: {', '.join(spec.options)}")
        return lowered
    if spec.kind == "string":
        return text
    raise PackageError("Runtime Settings schema is unavailable.")


def _default_payload_value(spec: RuntimeSettingSpec) -> str:
    return normalize_payload_value(spec, spec.default)


def validate_values(values: object, specs: dict[str, RuntimeSettingSpec]) -> dict[str, str]:
    if not isinstance(values, dict):
        raise PackageError("Runtime settings values must be an object.")
    unknown = sorted(set(values) - set(specs))
    if unknown:
        raise PackageError("Unknown runtime setting(s): " + ", ".join(unknown))
    normalized = {
        key: normalize_payload_value(specs[key], raw)
        for key, raw in values.items()
    }
    effective = {key: _default_payload_value(spec) for key, spec in specs.items()}
    effective.update(normalized)
    return normalized


def _read_limited_utf8(path: Path, label: str, *, missing_is_empty: bool = False) -> str:
    return read_limited_utf8(
        path,
        label,
        max_bytes=MAX_PACKAGE_BYTES,
        missing_is_empty=missing_is_empty,
        error=PackageError,
    )


def _read_persisted_values(path: Path, specs: dict[str, RuntimeSettingSpec]) -> dict[str, str]:
    """Read stored settings while tolerating retired local keys."""

    source = _read_limited_utf8(path, "Runtime settings file", missing_is_empty=True)
    raw_values: dict[str, str] = {}
    for line_number, line in enumerate(source.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            raise PackageError(f"Runtime settings file has invalid content at line {line_number}.")
        key, raw = stripped.split("=", 1)
        key = key.strip()
        raw = raw.strip()
        if key in RETIRED_PERSISTED_SETTINGS:
            continue
        if key not in specs or key in raw_values:
            raise PackageError(f"Runtime settings file has invalid content at line {line_number}.")
        # JSON settings are canonicalized by their own parser, so a '#' in a
        # quoted value (for example an API key) is data rather than an env-file
        # comment marker. Other setting kinds retain the line-oriented format.
        if specs[key].kind != "json" and "#" in stripped:
            raise PackageError(f"Runtime settings file has invalid content at line {line_number}.")
        raw_values[key] = raw
    return raw_values


def read_settings_file(path: Path, specs: dict[str, RuntimeSettingSpec]) -> dict[str, str]:
    """Read a complete effective settings snapshot for the Runtime Settings UI."""

    raw_values = _read_persisted_values(path, specs)

    values = {key: _default_payload_value(spec) for key, spec in specs.items()}
    for key, raw in raw_values.items():
        spec = specs[key]
        if spec.kind in {"mb", "optional_mb"}:
            if spec.kind == "optional_mb" and not raw.strip():
                values[key] = ""
                continue
            if not re.fullmatch(r"\d+", raw):
                raise PackageError(f"{key} must be stored as integer bytes.")
            stored_bytes = int(raw)
            minimum_bytes = int(round(float(spec.minimum or 0) * 1024 * 1024))
            maximum_bytes = int(round(float(spec.maximum or 0) * 1024 * 1024))
            if stored_bytes < minimum_bytes or stored_bytes > maximum_bytes:
                raise PackageError(f"{key} is outside its allowed range.")
            values[key] = _number_text(stored_bytes / (1024 * 1024))
        elif spec.kind == "json":
            encoded = raw.removeprefix("base64:")
            if encoded != raw:
                padding = "=" * ((4 - len(encoded) % 4) % 4)
                try:
                    if not re.fullmatch(r"[A-Za-z0-9_-]*", encoded):
                        raise ValueError("invalid base64 characters")
                    raw = base64.b64decode(
                        encoded + padding,
                        altchars=b"-_",
                        validate=True,
                    ).decode("utf-8")
                except (binascii.Error, ValueError, UnicodeDecodeError) as exc:
                    raise PackageError(f"{key} contains invalid encoded JSON.") from exc
            values[key] = normalize_payload_value(spec, raw)
        else:
            values[key] = normalize_payload_value(spec, raw)
    return validate_values(values, specs)


def read_configured_settings_file(path: Path, specs: dict[str, RuntimeSettingSpec]) -> dict[str, str]:
    """Return validated persisted values without retired keys."""

    raw_values = _read_persisted_values(path, specs)
    effective = read_settings_file(path, specs)
    configured: dict[str, str] = {}
    for key, raw in raw_values.items():
        spec = specs[key]
        configured[key] = raw if spec.kind in {"mb", "optional_mb"} else effective[key]
    return configured


def stored_value(spec: RuntimeSettingSpec, value: str) -> str:
    """Encode one effective value exactly as the settings file stores it."""

    if spec.kind == "json":
        encoded = base64.urlsafe_b64encode(value.encode("utf-8")).decode("ascii").rstrip("=")
        return f"base64:{encoded}"
    if spec.kind not in {"mb", "optional_mb"}:
        return value
    if spec.kind == "optional_mb" and not value.strip():
        return ""
    try:
        bytes_value = round(float(value) * 1024 * 1024)
    except (TypeError, ValueError, OverflowError):
        raise PackageError(f"{spec.key} must be stored as integer bytes.") from None
    return str(bytes_value)


def render_settings_file(specs: dict[str, RuntimeSettingSpec], values: Mapping[str, str]) -> str:
    """Render a complete settings document, skipping values at their default."""

    normalized = {key: _default_payload_value(spec) for key, spec in specs.items()}
    normalized.update(validate_values(dict(values), specs))
    lines = [RUNTIME_SETTINGS_HEADER]
    for key, spec in specs.items():
        value = normalized[key]
        if value == _default_payload_value(spec):
            continue
        lines.append(f"{key}={stored_value(spec, value)}")
    return "\n".join(lines) + "\n"


def write_settings_file(
    path: Path,
    specs: dict[str, RuntimeSettingSpec],
    values: Mapping[str, str],
) -> None:
    """Replace the settings file with one validated document."""

    from .persistence import atomic_write_text

    atomic_write_text(path, render_settings_file(specs, values))
