"""Bundled Runtime Settings schema used by the Python Core.

Keep display metadata and validation constraints in importable Python data so
Runtime Settings works identically in a portable Core bundle.
"""

from __future__ import annotations

from typing import Final


RUNTIME_SETTINGS_SCHEMA: Final[tuple[dict[str, object], ...]] = (
    {'key': 'YOUNG_ROUTER_REQUEST_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Request timeout', 'unit': 'seconds', 'kind': 'float', 'default': '7200', 'minimum': 0, 'maximum': 7200, 'help': 'Overall timeout for upstream model requests, continuation synthesis, and each recovery probe. 0 disables the local request cap.'},
    {'key': 'YOUNG_ROUTER_STREAM_START_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'First-event timeout', 'unit': 'seconds', 'kind': 'float', 'default': '120', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum wait for the first upstream stream event on ordinary requests. 0 falls back to Request timeout.'},
    {'key': 'YOUNG_ROUTER_HEAVY_REPLAY_STREAM_START_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Heavy-replay first-event', 'unit': 'seconds', 'kind': 'float', 'default': '300', 'minimum': 0, 'maximum': 3600, 'help': 'Raised first-event budget for Responses requests whose serialized replay prefix exceeds the heavy-replay threshold. A multi-megabyte signed history legitimately delays the first event on every route at once. 0 keeps only First-event timeout.'},
    {'key': 'YOUNG_ROUTER_HEAVY_REPLAY_STREAM_START_THRESHOLD_BYTES', 'category': 'Timeouts', 'label': 'Heavy-replay threshold', 'unit': 'bytes', 'kind': 'int', 'default': '1048576', 'minimum': 0, 'maximum': 268435456, 'help': 'Serialized replay weight (input plus instructions) at which Heavy-replay first-event applies. 0 disables the raised budget entirely.'},
    {'key': 'YOUNG_ROUTER_CODEX_COMPACTION_START_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Compaction first-event', 'unit': 'seconds', 'kind': 'float', 'default': '300', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum wait for the first event from a structured Codex compaction request. 0 falls back to Request timeout.'},
    {'key': 'YOUNG_ROUTER_STALL_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Stream idle timeout', 'unit': 'seconds', 'kind': 'float', 'default': '120', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum gap between stream events after the first event has arrived. 0 disables the local stream-idle cap.'},
    {'key': 'YOUNG_ROUTER_STREAM_KEEPALIVE_INTERVAL_SECONDS', 'category': 'Timeouts', 'label': 'Stream keepalive interval', 'unit': 'seconds', 'kind': 'float', 'default': '15', 'minimum': 0, 'maximum': 3600, 'help': 'While the delivery stream is silent, emit one parser-safe keepalive event per interval so client-side byte-idle timers do not fire before the proxy budgets do. 0 disables the heartbeat.'},
    {'key': 'YOUNG_ROUTER_CODEX_DESCENDANT_CLEANUP', 'category': 'Recovery', 'label': 'Codex parent completion barrier', 'kind': 'bool', 'default': '1', 'help': 'Require a fresh full descendant snapshot before a root Codex task can end. Required implementation and test work is awaited; descendants that no longer affect the deliverable are interrupted deepest-first. Disable to use the native Codex lifecycle only.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_MAX_SECONDS', 'category': 'Recovery', 'label': 'Recovery max', 'unit': 'seconds', 'kind': 'float', 'default': '14400', 'minimum': 0, 'maximum': 86400, 'help': 'Maximum route recovery polling time. The same connection stays alive with progress heartbeats while every route is cooling down, then retries after the first cooldown ends. 0 disables polling.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_INTERVAL_SECONDS', 'category': 'Timeouts', 'label': 'Recovery interval', 'unit': 'seconds', 'kind': 'float', 'default': '5', 'minimum': 0.001, 'maximum': 3600, 'help': 'Delay between real route recovery probes.'},
    {'key': 'YOUNG_ROUTER_SAME_DEPLOYMENT_RETRIES', 'category': 'Recovery', 'label': 'Same-route retries', 'unit': 'retries', 'kind': 'int', 'default': '0', 'minimum': 0, 'maximum': 20, 'help': 'Additional attempts on the failed deployment before the next peer or order. Default 0 advances immediately; this also overrides LiteLLM Router retry-policy counts.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_POLICY_BALANCE', 'category': 'Recovery', 'label': 'Balance / quota', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How insufficient balance, quota, or billing failures are handled.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_POLICY_RATE_LIMIT', 'category': 'Recovery', 'label': 'Rate limit / overload', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How HTTP 429 and upstream overload or capacity failures are handled. Default recovery retries without cooling down the deployment.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_POLICY_SERVER', 'category': 'Recovery', 'label': 'Server / gateway', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How temporary server failures, no healthy route, and gateway timeouts are handled.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_POLICY_NETWORK', 'category': 'Recovery', 'label': 'Network', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How disconnects, DNS failures, and connection errors are handled. Default recovery does not cool down the deployment.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_POLICY_STREAM_START_TIMEOUT', 'category': 'Recovery', 'label': 'First-event timeout', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How a local timeout before the first upstream stream event is handled.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_POLICY_STREAM_IDLE_TIMEOUT', 'category': 'Recovery', 'label': 'Stream idle timeout', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How a local timeout after streaming has begun is handled. Default recovery does not cool down the deployment.'},
    {'key': 'YOUNG_ROUTER_RECOVERY_POLICY_REQUEST_ERROR', 'category': 'Recovery', 'label': 'Request / format error', 'kind': 'enum', 'default': 'error', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How deterministic request, format, model, policy, and context errors are handled. Default error returns a terminal failure so the proxy can be patched instead of waiting.'},
    {'key': 'YOUNG_ROUTER_WEB_FETCH_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Web fetch timeout', 'unit': 'seconds', 'kind': 'float', 'default': '12', 'minimum': 3, 'maximum': 60, 'help': 'Timeout for pi-web-access searches and model-selected source-page fetches. This does not cap model generation.'},
    {'key': 'YOUNG_ROUTER_WEB_SEARCH_MAX_RESULTS', 'category': 'Web Search', 'label': 'Search results', 'unit': 'results', 'kind': 'int', 'default': '5', 'minimum': 1, 'maximum': 20, 'help': 'Maximum pi-web-access results returned for each search action.'},
    {'key': 'YOUNG_ROUTER_WEB_SEARCH_READ_CHARS', 'category': 'Web Search', 'label': 'Readable page chars', 'unit': 'chars', 'kind': 'int', 'default': '1400', 'minimum': 200, 'maximum': 5000, 'help': 'Maximum pi-web-access source-page characters returned after the model explicitly opens a result page. A model-directed page find scans up to 12000 characters to avoid false negatives.'},
    {'key': 'YOUNG_ROUTER_WEB_SEARCH_MAX_ROUNDS', 'category': 'Web Search', 'label': 'Action rounds', 'unit': 'rounds', 'kind': 'int', 'default': '4', 'minimum': 1, 'maximum': 8, 'help': 'Maximum model-directed web-search action rounds for one response. Four rounds leave the model a turn to inspect a source found after changed queries.'},
    {'key': 'YOUNG_ROUTER_WEB_SEARCH_MAX_QUERIES', 'category': 'Web Search', 'label': 'Total queries', 'unit': 'queries', 'kind': 'int', 'default': '16', 'minimum': 1, 'maximum': 64, 'help': 'Maximum unique search queries across all web-search rounds.'},
    {'key': 'YOUNG_ROUTER_WEB_SEARCH_MAX_OPEN_PAGES', 'category': 'Web Search', 'label': 'Open pages', 'unit': 'pages', 'kind': 'int', 'default': '8', 'minimum': 0, 'maximum': 32, 'help': 'Maximum explicit page-open actions across all web-search rounds. 0 disables page opens.'},
    {'key': 'YOUNG_ROUTER_WEB_SEARCH_MAX_FIND_IN_PAGE', 'category': 'Web Search', 'label': 'Find in page', 'unit': 'actions', 'kind': 'int', 'default': '12', 'minimum': 0, 'maximum': 64, 'help': 'Maximum find-in-page actions across all web-search rounds. 0 disables in-page find.'},
    {'key': 'YOUNG_ROUTER_EXTERNAL_WEB_SEARCH_MODEL_RETRIES', 'category': 'Web Search', 'label': 'Model retries', 'unit': 'retries', 'kind': 'int', 'default': '2', 'minimum': 0, 'maximum': 5, 'help': 'Retries for temporary rate-limit failures while the model plans or synthesizes bridged web search.'},
    {'key': 'YOUNG_ROUTER_EXTERNAL_WEB_SEARCH_MODEL_RETRY_DELAY_SECONDS', 'category': 'Web Search', 'label': 'Model retry delay', 'unit': 'seconds', 'kind': 'float', 'default': '1', 'minimum': 0, 'maximum': 30, 'help': 'Base delay between temporary web-search model retries.'},
    {'key': 'YOUNG_ROUTER_PI_WEB_ACCESS_CONFIG_JSON', 'category': 'Web Search', 'label': 'pi-web-access config JSON', 'kind': 'json', 'default': '{}', 'secret': True, 'retain_existing': '__YOUNG_ROUTER_RETAIN_EXISTING__', 'help': 'JSON configuration passed to pi-web-access. It is stored privately and written to the managed web-search.json file before the proxy starts.'},
    {'key': 'YOUNG_ROUTER_DSH_VISION_ROUTER_ENABLED', 'category': 'Vision Router', 'label': 'dsh-vision-router enabled', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'on', 'off'], 'help': 'Enable or disable the fallback router. This control and enabled in the advanced JSON update each other.'},
    {'key': 'YOUNG_ROUTER_DSH_VISION_ROUTER_BACKEND', 'category': 'Vision Router', 'label': 'dsh-vision-router backend', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'auto', 'local', 'api', 'off'], 'help': 'Select the fallback backend. This control and backend in the advanced JSON update each other; auto tries configured local and HTTP providers, local uses local providers/OCR only, and API uses configured HTTP providers.'},
    {'key': 'YOUNG_ROUTER_DSH_VISION_ROUTER_FREE_FALLBACK', 'category': 'Vision Router', 'label': 'Use free fallback chain', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'on', 'off'], 'help': 'Enable or disable the built-in no-key HTTP fallback chain. This control and freeFallback in the advanced JSON update each other.'},
    {'key': 'YOUNG_ROUTER_DSH_VISION_ROUTER_TIMEOUT_SECONDS', 'category': 'Vision Router', 'label': 'Vision fallback timeout', 'unit': 'seconds', 'kind': 'optional_int', 'default': '', 'minimum': 1, 'maximum': 600, 'help': 'Maximum time allowed for each vision fallback provider request. Editing this value updates timeoutSeconds in the advanced JSON, and editing JSON updates this value.'},
    {'key': 'YOUNG_ROUTER_DSH_VISION_ROUTER_MAX_TOKENS', 'category': 'Vision Router', 'label': 'Vision fallback tokens', 'unit': 'tokens', 'kind': 'optional_int', 'default': '', 'minimum': 1, 'maximum': 32768, 'help': 'Maximum generated tokens for vision fallback requests. Editing this value updates maxTokens in the advanced JSON, and editing JSON updates this value.'},
    {'key': 'YOUNG_ROUTER_DSH_VISION_ROUTER_LOCAL_OLLAMA_ENABLED', 'category': 'Vision Router', 'label': 'Enable local Ollama', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'on', 'off'], 'help': 'Try the local Ollama vision provider before configured HTTP providers. This control and localOllama.enabled in the advanced JSON update each other; endpoint and model remain editable there.'},
    {'key': 'YOUNG_ROUTER_DSH_VISION_ROUTER_LOCAL_LM_STUDIO_ENABLED', 'category': 'Vision Router', 'label': 'Enable local LM Studio', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'on', 'off'], 'help': 'Try the local LM Studio vision provider before configured HTTP providers. This control and localLmStudio.enabled in the advanced JSON update each other; endpoint and model remain editable there.'},
    {'key': 'YOUNG_ROUTER_DSH_VISION_ROUTER_CONFIG_JSON', 'category': 'Vision Router', 'label': 'dsh-vision-router config', 'kind': 'json', 'default': '{"enabled":true,"backend":"auto","freeFallback":true,"timeoutSeconds":45,"maxTokens":4096,"providers":[],"httpProviders":[],"localOllama":{"enabled":false},"localLmStudio":{"enabled":false}}', 'secret': True, 'retain_existing': '__YOUNG_ROUTER_RETAIN_EXISTING__', 'help': 'Advanced JSON for the portable dsh-vision-router fallback chain. Configure provider endpoints, models, apiKeyEnv references, prompt, provider order, and local provider details. The quick controls above and matching JSON fields update each other. It runs only after the selected model rejects image input; a model advertising vision is sent the original image unchanged.'},
    {'key': 'YOUNG_ROUTER_UNKNOWN_MODEL_CONTEXT_WINDOW', 'category': 'Model Context', 'label': 'Unknown model raw context', 'unit': 'tokens', 'kind': 'int', 'default': '272000', 'minimum': 1, 'maximum': 16000000, 'help': 'Raw Codex context window used when no bundled, route, LiteLLM, or upstream metadata matches a model. 272000 displays about 258k at Codex’s 95% effective-window policy.'},
    {'key': 'YOUNG_ROUTER_MODEL_CONTEXT_REFRESH_HOURS', 'category': 'Model Context', 'label': 'Model context refresh', 'unit': 'hours', 'kind': 'int', 'default': '6', 'minimum': 0, 'maximum': 720, 'help': 'How often the managed Codex catalog refreshes public model-context metadata. 0 keeps the bundled and cached registry offline.'},
    {'key': 'YOUNG_ROUTER_CATALOG_BASE_PROFILE', 'category': 'Model Context', 'label': 'Catalog base profile', 'kind': 'string', 'default': '', 'hidden': True, 'help': 'Internal pin for the native Codex profile that third-party model aliases inherit. Written by Core and replaced only when the installed client no longer offers that profile; do not edit.'},
    {'key': 'YOUNG_ROUTER_DEPLOYMENT_COOLDOWN_FAILURES', 'category': 'Fallback', 'label': 'Cooldown failures', 'unit': 'failures', 'kind': 'int', 'default': '2', 'minimum': 0, 'maximum': 20, 'help': 'Consecutive upstream failures before that deployment is temporarily skipped. 0 disables cooldown.'},
    {'key': 'YOUNG_ROUTER_DEPLOYMENT_COOLDOWN_SECONDS', 'category': 'Fallback', 'label': 'Cooldown duration', 'unit': 'seconds', 'kind': 'float', 'default': '300', 'minimum': 0, 'maximum': 86400, 'help': 'How long a failed deployment is skipped after reaching the threshold. 0 disables cooldown.'},
    {'key': 'YOUNG_ROUTER_SESSION_DEPLOYMENT_AFFINITY', 'category': 'Fallback', 'label': 'Session deployment affinity', 'kind': 'bool', 'default': '1', 'help': 'Keep a session on the deployment that first served it so prompt-cache reuse and route stickiness stay stable across turns. Disable to select every turn by routing strategy alone.'},
    {'key': 'YOUNG_ROUTER_PROTOCOL_FALLBACK_TTL_SECONDS', 'category': 'Fallback', 'label': 'Backup protocol memory', 'unit': 'seconds', 'kind': 'float', 'default': '600', 'minimum': 0, 'maximum': 86400, 'help': 'After a backup protocol succeeds, reuse it for the same deployment and incoming protocol for this long before probing the incoming protocol again. 0 disables the memory.'},
    {'key': 'YOUNG_ROUTER_CODEX_COMPACTION_CAPABILITY_TTL_SECONDS', 'category': 'Fallback', 'label': 'Compaction capability memory', 'unit': 'seconds', 'kind': 'float', 'default': '1800', 'minimum': 0, 'maximum': 86400, 'help': 'How long to remember whether a Responses route can return encrypted Codex compaction. New tasks default to Codex’s local checkpoint summary (the LiteLLM selection keeps a neutral provider name); only a model with an explicit supports_responses_compaction opt-in advertises the exact OpenAI name, and its route is still verified by a tiny history-free probe before signed history is forwarded (official OpenAI hosts skip the probe). An unsupported deployment fails over to other candidates; when all candidates reject encrypted compaction the explicit protocol error is returned. Already-running tasks keep the capability they cached at task creation and cannot switch mid-protocol. 0 probes every compaction.'},
    {'key': 'YOUNG_ROUTER_WEB_SEARCH_UNSUPPORTED_TTL_SECONDS', 'category': 'Fallback', 'label': 'Web search unsupported memory', 'unit': 'seconds', 'kind': 'float', 'default': '600', 'minimum': 0, 'maximum': 86400, 'help': 'After a deployment explicitly rejects native web_search, use the local pi-web-access bridge for this long before probing native search again. Transient, network, quota, and provider-search failures do not populate this memory. 0 disables cross-request memory.'},
    {'key': 'YOUNG_ROUTER_REASONING_COMPAT_TTL_SECONDS', 'category': 'Fallback', 'label': 'Reasoning parameter compat memory', 'unit': 'seconds', 'kind': 'float', 'default': '1800', 'minimum': 0, 'maximum': 86400, 'help': 'How long a deployment keeps the wire shape that carries client reasoning parameters. A Gemini-family upstream that refuses the OpenAI reasoning fields for an aliased model name is first replayed with the native Google thinking configuration, which keeps the requested level; any other route is replayed without the reasoning fields and uses its provider default thinking. Only a deterministic rejection of the model’s thinking configuration populates this memory. 0 disables cross-request memory (each request pays the one replay again).'},
    {'key': 'YOUNG_ROUTER_DEPLOYMENT_COOLDOWN_ORDINARY_ENABLED', 'category': 'Fallback', 'label': 'Ordinary requests write cooldown', 'kind': 'bool', 'default': '1', 'help': 'Whether failed ordinary requests add failures to the shared deployment cooldown pool. Existing cooldowns are still read by every request type.'},
    {'key': 'YOUNG_ROUTER_DEPLOYMENT_COOLDOWN_COMPACTION_ENABLED', 'category': 'Fallback', 'label': 'Compaction requests write cooldown', 'kind': 'bool', 'default': '0', 'help': 'Whether failed structured Codex compaction requests add failures to the shared deployment cooldown pool. Disabled by default so a compaction-specific upstream failure does not cool a route for ordinary work.'},
    {'key': 'YOUNG_ROUTER_IMAGE_TOOL_UNSUPPORTED_TTL_SECONDS', 'category': 'Fallback', 'label': 'Image tool unsupported memory', 'unit': 'seconds', 'kind': 'float', 'default': '600', 'minimum': 0, 'maximum': 86400, 'help': 'How long a deployment is skipped after a deterministic image_generation capability rejection. Parameter errors, timeouts, policy failures, and other upstream errors do not populate this memory. 0 disables cross-request memory.'},
    {'key': 'YOUNG_ROUTER_PREFIX_IMAGE_PREVIEW_ENABLED', 'category': 'Fallback', 'label': 'Prefix image previews', 'kind': 'bool', 'default': '1', 'help': 'Replay oversized signed-prefix view_image outputs as deterministic previews plus local-path references instead of re-uploading the original bytes every turn; an explicit original-resolution output replays as that same bounded preview, and its original bytes never enter the replay (the path reference re-opens the file on demand). A referenced file the client may lose (a clipboard paste, an intermediate crop in temporary storage, a deleted file) is first copied into the durable replay-image cache, and an output whose copy cannot be written keeps its inline preview instead of a path reference it could never open.'},
    {'key': 'YOUNG_ROUTER_PREFIX_IMAGE_PREVIEW_MIN_BYTES', 'category': 'Fallback', 'label': 'Prefix image preview threshold', 'unit': 'bytes', 'kind': 'int', 'default': '131072', 'minimum': 1024, 'maximum': 16777216, 'help': 'Minimum inline image size before a signed-prefix view_image output is replayed as a preview. Smaller images are forwarded unchanged.'},
    {'key': 'YOUNG_ROUTER_PREFIX_IMAGE_MODE', 'category': 'Fallback', 'label': 'Prefix image mode', 'kind': 'enum', 'default': 'path-recent', 'options': ['preview', 'path-recent', 'off'], 'help': 'How signed-prefix view_image outputs are replayed. preview keeps a reduced preview for every oversized output; path-recent keeps previews only for the most recent image outputs and replaces older ones with pure local-path references; off disables the rewriting entirely. The model can always re-open any original with view_image, and an original that only existed in temporary storage is replaced by a durable local copy so that stays true after the system cleans up its file.'},
    {'key': 'YOUNG_ROUTER_PREFIX_IMAGE_RECENT_COUNT', 'category': 'Fallback', 'label': 'Prefix image recent count', 'unit': 'images', 'kind': 'int', 'default': '6', 'minimum': 0, 'maximum': 64, 'help': 'In path-recent mode, how many of the most recent image outputs keep an inline preview; older outputs become pure path references. 0 turns every oversized output into a path reference.'},
    {'key': 'YOUNG_ROUTER_PREFIX_IMAGE_ORIGINAL_PATH', 'category': 'Fallback', 'label': 'Path-convert original-resolution images', 'kind': 'bool', 'default': '1', 'help': 'In path-recent mode, view_image outputs explicitly requested at original resolution join the same preview/path conversion as every other output: a bounded inline preview plus the matching path inside the recent window, and a pure local-path reference beyond it. Disable to replay explicit original-resolution requests unchanged.'},
    {'key': 'YOUNG_ROUTER_MCP_AUTO_APPROVE', 'category': 'MCP', 'label': 'Auto-approve MCP tools', 'kind': 'bool', 'default': '0', 'help': 'When enabled, set Responses API MCP tools to require_approval=never so the upstream service does not pause for interactive approval. Disabled by default because it bypasses MCP safety review.'},
    {'key': 'YOUNG_ROUTER_LOG_MAX_BYTES', 'category': 'Logs', 'label': 'Local log file cap', 'unit': 'MB', 'kind': 'mb', 'default': '10', 'minimum': 0.25, 'maximum': 100, 'help': 'Per-file cap for local logs: recent requests, service stdout/stderr, and menu actions. On rotation each log keeps the configured number of older tails as .1..N backups.'},
    {'key': 'YOUNG_ROUTER_LOG_BACKUP_SEGMENTS', 'category': 'Logs', 'label': 'Log backup segments', 'unit': 'segments', 'kind': 'int', 'default': '2', 'minimum': 1, 'maximum': 8, 'help': 'Number of previous tails kept as .1..N when a local log rotates. 1 keeps only the immediately preceding tail; the current file is always kept.'},
    {'key': 'YOUNG_ROUTER_LOG_VIEW_LIMIT', 'category': 'Logs', 'label': 'Log view rows', 'unit': 'rows', 'kind': 'int', 'default': '10000', 'minimum': 100, 'maximum': 100000, 'help': 'Maximum rows shown per log tab. This changes the view only and does not delete local log data.'},
    {'key': 'YOUNG_ROUTER_LOG_REQUEST_STALE_SECONDS', 'category': 'Logs', 'label': 'Request row stale window', 'unit': 'seconds', 'kind': 'float', 'default': '900', 'minimum': 0, 'maximum': 86400, 'help': 'How long a request row may stay unfinished without progress before the log reports it as interrupted. A client disconnect, a failover teardown, or a service restart can end an upstream attempt without a terminal callback; this window closes those rows instead of showing "sending" forever. 0 keeps unfinished rows open.'},
    {'key': 'YOUNG_ROUTER_ROUTE_TRACE_PREVIEW_CHARS', 'category': 'Logs', 'label': 'Trace preview chars', 'unit': 'chars', 'kind': 'int', 'default': '2000', 'minimum': 80, 'maximum': 2000, 'help': 'Maximum request-preview characters retained in the always-on local route trace.'},
    {'key': 'LITELLM_USE_SYSTEM_PROXIES', 'category': 'Network', 'label': 'Use system proxies', 'kind': 'bool', 'default': '0', 'help': 'Allow upstream HTTP clients to use macOS system proxy settings. Off isolates LiteLLM from system proxy auto-discovery.'},
    {'key': 'LITELLM_PORT', 'category': 'Service', 'label': 'Local port', 'kind': 'int', 'default': '12390', 'minimum': 1, 'maximum': 65535, 'hidden': True, 'help': 'Local HTTP port for the LiteLLM proxy. When the port is occupied the service steps forward to the next free port. Configure it in General settings.'},
    {'key': 'YOUNG_ROUTER_WEBSOCKET_MAX_FRAME_BYTES', 'category': 'Service', 'label': 'WebSocket frame limit', 'unit': 'bytes', 'kind': 'int', 'default': '67108864', 'minimum': 1048576, 'maximum': 1073741824, 'help': 'Maximum inbound WebSocket message frame accepted by the local proxy. Codex sends each Responses turn request, including the signed replay history, as one frame; a smaller limit closes it with code 1009 before routing and Codex reconnects in a loop. Requires a service restart.'},
    {'key': 'LITELLM_NUM_WORKERS', 'category': 'Service', 'label': 'Worker count', 'unit': 'workers', 'kind': 'int', 'default': '16', 'minimum': 1, 'maximum': 64, 'help': 'Young Router runs 16 Uvicorn workers by default. Keep this value at 16 unless the user explicitly changes the service concurrency setting.'},
    {'key': 'LITELLM_HEALTH_WAIT_SECONDS', 'category': 'Service', 'label': 'Health wait', 'unit': 'seconds', 'kind': 'int', 'default': '60', 'minimum': 1, 'maximum': 600, 'help': 'How long start/restart waits for the health endpoint before the started process is torn down.'},
    {'key': 'YOUNG_ROUTER_RELAY_SESSION_RECHECK_SECONDS', 'category': 'Service', 'label': 'Relay session re-check window', 'unit': 'seconds', 'kind': 'float', 'default': '60', 'minimum': 0, 'maximum': 3600, 'help': 'How long one relay login observation answers later checks of the same account. Opening the account pane re-checks its station session on every mount, and each check is a station round trip; inside this window the pane reuses the session it already verified, so re-entering the pane does not re-authenticate, re-read the site, or repaint the login state. 0 re-checks on every mount, because then the window is only as long as the reuse the account pane already does.'},
)


def runtime_settings_metadata() -> list[dict[str, object]]:
    """Return a defensive copy for UI projection and validation."""

    return [dict(item) for item in RUNTIME_SETTINGS_SCHEMA]
