// Generated by rn/scripts/gen-native-specs.mjs from ui/nativeSpecs/NativePicker.spec.ts;
// edit the source file, not this one.

import { codegenNativeComponent } from "react-native";
import type { ViewProps } from "react-native";
import type {
  DirectEventHandler,
  Int32,
  WithDefault,
} from "react-native/Libraries/Types/CodegenTypes";

type ChangeEvent = Readonly<{ index: Int32; value: string }>;

export interface NativePickerProps extends ViewProps {
  labels: ReadonlyArray<string>;
  selectedValue: string;
  disabled?: WithDefault<boolean, false>;
  compact?: WithDefault<boolean, false>;
  onChange?: DirectEventHandler<ChangeEvent>;
}

export default codegenNativeComponent<NativePickerProps>("LiteLLMAppKitPicker");
