"""Bundled Runtime Settings schema used by the Python Core.

Keep display metadata and validation constraints in importable Python data so
Runtime Settings works identically in a portable Core bundle.
"""

from __future__ import annotations

from typing import Final


RUNTIME_SETTINGS_SCHEMA: Final[tuple[dict[str, object], ...]] = (
    {'key': 'LITELLM_MENU_RELAY_AUTO_GROUP_INTERVAL_MINUTES', 'category': 'Relay', 'label': 'Automatic grouping interval', 'unit': 'minutes', 'kind': 'int', 'default': '30', 'minimum': 1, 'maximum': 1440, 'help': 'How often the Relay Management view refreshes and stages automatic API-key grouping.'},
    {'key': 'LITELLM_MENU_REQUEST_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Request timeout', 'unit': 'seconds', 'kind': 'float', 'default': '7200', 'minimum': 0, 'maximum': 7200, 'help': 'Overall timeout for upstream model requests, continuation synthesis, and each recovery probe. 0 disables the local request cap.'},
    {'key': 'LITELLM_MENU_STREAM_START_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'First-event timeout', 'unit': 'seconds', 'kind': 'float', 'default': '120', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum wait for the first upstream stream event on ordinary requests. 0 falls back to Request timeout.'},
    {'key': 'LITELLM_MENU_HEAVY_REPLAY_STREAM_START_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Heavy-replay first-event', 'unit': 'seconds', 'kind': 'float', 'default': '300', 'minimum': 0, 'maximum': 3600, 'help': 'Raised first-event budget for Responses requests whose serialized replay prefix exceeds the heavy-replay threshold. A multi-megabyte signed history legitimately delays the first event on every route at once. 0 keeps only First-event timeout.'},
    {'key': 'LITELLM_MENU_HEAVY_REPLAY_STREAM_START_THRESHOLD_BYTES', 'category': 'Timeouts', 'label': 'Heavy-replay threshold', 'unit': 'bytes', 'kind': 'int', 'default': '1048576', 'minimum': 0, 'maximum': 268435456, 'help': 'Serialized replay weight (input plus instructions) at which Heavy-replay first-event applies. 0 disables the raised budget entirely.'},
    {'key': 'LITELLM_MENU_CODEX_COMPACTION_START_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Compaction first-event', 'unit': 'seconds', 'kind': 'float', 'default': '300', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum wait for the first event from a structured Codex compaction request. 0 falls back to Request timeout.'},
    {'key': 'LITELLM_MENU_STALL_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Stream idle timeout', 'unit': 'seconds', 'kind': 'float', 'default': '120', 'minimum': 0, 'maximum': 3600, 'help': 'Maximum gap between stream events after the first event has arrived. 0 disables the local stream-idle cap.'},
    {'key': 'LITELLM_MENU_CODEX_DESCENDANT_CLEANUP', 'category': 'Recovery', 'label': 'Codex parent completion barrier', 'kind': 'bool', 'default': '1', 'help': 'Require a fresh full descendant snapshot before a root Codex task can end. Required implementation and test work is awaited; descendants that no longer affect the deliverable are interrupted deepest-first. Disable to use the native Codex lifecycle only.'},
    {'key': 'LITELLM_MENU_RECOVERY_MAX_SECONDS', 'category': 'Recovery', 'label': 'Recovery max', 'unit': 'seconds', 'kind': 'float', 'default': '14400', 'minimum': 0, 'maximum': 86400, 'help': 'Maximum route recovery polling time. The same connection stays alive with progress heartbeats while every route is cooling down, then retries after the first cooldown ends. 0 disables polling.'},
    {'key': 'LITELLM_MENU_RECOVERY_INTERVAL_SECONDS', 'category': 'Timeouts', 'label': 'Recovery interval', 'unit': 'seconds', 'kind': 'float', 'default': '5', 'minimum': 0.001, 'maximum': 3600, 'help': 'Delay between real route recovery probes.'},
    {'key': 'LITELLM_MENU_SAME_DEPLOYMENT_RETRIES', 'category': 'Recovery', 'label': 'Same-route retries', 'unit': 'retries', 'kind': 'int', 'default': '0', 'minimum': 0, 'maximum': 20, 'help': 'Additional attempts on the failed deployment before the next peer or order. Default 0 advances immediately; this also overrides LiteLLM Router retry-policy counts.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_BALANCE', 'category': 'Recovery', 'label': 'Balance / quota', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How insufficient balance, quota, or billing failures are handled.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_RATE_LIMIT', 'category': 'Recovery', 'label': 'Rate limit / overload', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How HTTP 429 and upstream overload or capacity failures are handled. Default recovery retries without cooling down the deployment.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_SERVER', 'category': 'Recovery', 'label': 'Server / gateway', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How temporary server failures, no healthy route, and gateway timeouts are handled.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_NETWORK', 'category': 'Recovery', 'label': 'Network', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How disconnects, DNS failures, and connection errors are handled. Default recovery does not cool down the deployment.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_STREAM_START_TIMEOUT', 'category': 'Recovery', 'label': 'First-event timeout', 'kind': 'enum', 'default': 'recovery_cooldown', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How a local timeout before the first upstream stream event is handled.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_STREAM_IDLE_TIMEOUT', 'category': 'Recovery', 'label': 'Stream idle timeout', 'kind': 'enum', 'default': 'recovery', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How a local timeout after streaming has begun is handled. Default recovery does not cool down the deployment.'},
    {'key': 'LITELLM_MENU_RECOVERY_POLICY_REQUEST_ERROR', 'category': 'Recovery', 'label': 'Request / format error', 'kind': 'enum', 'default': 'error', 'options': ['error', 'recovery', 'recovery_cooldown'], 'help': 'How deterministic request, format, model, policy, and context errors are handled. Default error returns a terminal failure so the proxy can be patched instead of waiting.'},
    {'key': 'LITELLM_MENU_WEB_FETCH_TIMEOUT_SECONDS', 'category': 'Timeouts', 'label': 'Web fetch timeout', 'unit': 'seconds', 'kind': 'float', 'default': '12', 'minimum': 3, 'maximum': 60, 'help': 'Timeout for pi-web-access searches and model-selected source-page fetches. This does not cap model generation.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_RESULTS', 'category': 'Web Search', 'label': 'Search results', 'unit': 'results', 'kind': 'int', 'default': '5', 'minimum': 1, 'maximum': 20, 'help': 'Maximum pi-web-access results returned for each search action.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_READ_CHARS', 'category': 'Web Search', 'label': 'Readable page chars', 'unit': 'chars', 'kind': 'int', 'default': '1400', 'minimum': 200, 'maximum': 5000, 'help': 'Maximum pi-web-access source-page characters returned after the model explicitly opens a result page. A model-directed page find scans up to 12000 characters to avoid false negatives.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_ROUNDS', 'category': 'Web Search', 'label': 'Action rounds', 'unit': 'rounds', 'kind': 'int', 'default': '4', 'minimum': 1, 'maximum': 8, 'help': 'Maximum model-directed web-search action rounds for one response. Four rounds leave the model a turn to inspect a source found after changed queries.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_QUERIES', 'category': 'Web Search', 'label': 'Total queries', 'unit': 'queries', 'kind': 'int', 'default': '16', 'minimum': 1, 'maximum': 64, 'help': 'Maximum unique search queries across all web-search rounds.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_OPEN_PAGES', 'category': 'Web Search', 'label': 'Open pages', 'unit': 'pages', 'kind': 'int', 'default': '8', 'minimum': 0, 'maximum': 32, 'help': 'Maximum explicit page-open actions across all web-search rounds. 0 disables page opens.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_MAX_FIND_IN_PAGE', 'category': 'Web Search', 'label': 'Find in page', 'unit': 'actions', 'kind': 'int', 'default': '12', 'minimum': 0, 'maximum': 64, 'help': 'Maximum find-in-page actions across all web-search rounds. 0 disables in-page find.'},
    {'key': 'LITELLM_MENU_EXTERNAL_WEB_SEARCH_MODEL_RETRIES', 'category': 'Web Search', 'label': 'Model retries', 'unit': 'retries', 'kind': 'int', 'default': '2', 'minimum': 0, 'maximum': 5, 'help': 'Retries for temporary rate-limit failures while the model plans or synthesizes bridged web search.'},
    {'key': 'LITELLM_MENU_EXTERNAL_WEB_SEARCH_MODEL_RETRY_DELAY_SECONDS', 'category': 'Web Search', 'label': 'Model retry delay', 'unit': 'seconds', 'kind': 'float', 'default': '1', 'minimum': 0, 'maximum': 30, 'help': 'Base delay between temporary web-search model retries.'},
    {'key': 'LITELLM_MENU_PI_WEB_ACCESS_CONFIG_JSON', 'category': 'Web Search', 'label': 'pi-web-access config JSON', 'kind': 'json', 'default': '{}', 'secret': True, 'retain_existing': '__LITELLM_MENU_RETAIN_EXISTING__', 'help': 'JSON configuration passed to pi-web-access. It is stored privately and written to the managed web-search.json file before the proxy starts.'},
    {'key': 'LITELLM_MENU_DSH_VISION_ROUTER_ENABLED', 'category': 'Vision Router', 'label': 'dsh-vision-router enabled', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'on', 'off'], 'help': 'Enable or disable the fallback router. This control and enabled in the advanced JSON update each other.'},
    {'key': 'LITELLM_MENU_DSH_VISION_ROUTER_BACKEND', 'category': 'Vision Router', 'label': 'dsh-vision-router backend', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'auto', 'local', 'api', 'off'], 'help': 'Select the fallback backend. This control and backend in the advanced JSON update each other; auto tries configured local and HTTP providers, local uses local providers/OCR only, and API uses configured HTTP providers.'},
    {'key': 'LITELLM_MENU_DSH_VISION_ROUTER_FREE_FALLBACK', 'category': 'Vision Router', 'label': 'Use free fallback chain', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'on', 'off'], 'help': 'Enable or disable the built-in no-key HTTP fallback chain. This control and freeFallback in the advanced JSON update each other.'},
    {'key': 'LITELLM_MENU_DSH_VISION_ROUTER_TIMEOUT_SECONDS', 'category': 'Vision Router', 'label': 'Vision fallback timeout', 'unit': 'seconds', 'kind': 'optional_int', 'default': '', 'minimum': 1, 'maximum': 600, 'help': 'Maximum time allowed for each vision fallback provider request. Editing this value updates timeoutSeconds in the advanced JSON, and editing JSON updates this value.'},
    {'key': 'LITELLM_MENU_DSH_VISION_ROUTER_MAX_TOKENS', 'category': 'Vision Router', 'label': 'Vision fallback tokens', 'unit': 'tokens', 'kind': 'optional_int', 'default': '', 'minimum': 1, 'maximum': 32768, 'help': 'Maximum generated tokens for vision fallback requests. Editing this value updates maxTokens in the advanced JSON, and editing JSON updates this value.'},
    {'key': 'LITELLM_MENU_DSH_VISION_ROUTER_LOCAL_OLLAMA_ENABLED', 'category': 'Vision Router', 'label': 'Enable local Ollama', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'on', 'off'], 'help': 'Try the local Ollama vision provider before configured HTTP providers. This control and localOllama.enabled in the advanced JSON update each other; endpoint and model remain editable there.'},
    {'key': 'LITELLM_MENU_DSH_VISION_ROUTER_LOCAL_LM_STUDIO_ENABLED', 'category': 'Vision Router', 'label': 'Enable local LM Studio', 'kind': 'enum', 'default': 'inherit', 'options': ['inherit', 'on', 'off'], 'help': 'Try the local LM Studio vision provider before configured HTTP providers. This control and localLmStudio.enabled in the advanced JSON update each other; endpoint and model remain editable there.'},
    {'key': 'LITELLM_MENU_DSH_VISION_ROUTER_CONFIG_JSON', 'category': 'Vision Router', 'label': 'dsh-vision-router config', 'kind': 'json', 'default': '{"enabled":true,"backend":"auto","freeFallback":true,"timeoutSeconds":45,"maxTokens":4096,"providers":[],"httpProviders":[],"localOllama":{"enabled":false},"localLmStudio":{"enabled":false}}', 'secret': True, 'retain_existing': '__LITELLM_MENU_RETAIN_EXISTING__', 'help': 'Advanced JSON for the portable dsh-vision-router fallback chain. Configure provider endpoints, models, apiKeyEnv references, prompt, provider order, and local provider details. The quick controls above and matching JSON fields update each other. It runs only after the selected model rejects image input; a model advertising vision is sent the original image unchanged.'},
    {'key': 'LITELLM_MENU_UNKNOWN_MODEL_CONTEXT_WINDOW', 'category': 'Model Context', 'label': 'Unknown model raw context', 'unit': 'tokens', 'kind': 'int', 'default': '272000', 'minimum': 1, 'maximum': 16000000, 'help': 'Raw Codex context window used when no bundled, route, LiteLLM, or upstream metadata matches a model. 272000 displays about 258k at Codex’s 95% effective-window policy.'},
    {'key': 'LITELLM_MENU_MODEL_CONTEXT_REFRESH_HOURS', 'category': 'Model Context', 'label': 'Model context refresh', 'unit': 'hours', 'kind': 'int', 'default': '6', 'minimum': 0, 'maximum': 720, 'help': 'How often the managed Codex catalog refreshes public model-context metadata. 0 keeps the bundled and cached registry offline.'},
    {'key': 'LITELLM_MENU_DEPLOYMENT_COOLDOWN_FAILURES', 'category': 'Fallback', 'label': 'Cooldown failures', 'unit': 'failures', 'kind': 'int', 'default': '2', 'minimum': 0, 'maximum': 20, 'help': 'Consecutive upstream failures before that deployment is temporarily skipped. 0 disables cooldown.'},
    {'key': 'LITELLM_MENU_DEPLOYMENT_COOLDOWN_SECONDS', 'category': 'Fallback', 'label': 'Cooldown duration', 'unit': 'seconds', 'kind': 'float', 'default': '300', 'minimum': 0, 'maximum': 86400, 'help': 'How long a failed deployment is skipped after reaching the threshold. 0 disables cooldown.'},
    {'key': 'LITELLM_MENU_PROTOCOL_FALLBACK_TTL_SECONDS', 'category': 'Fallback', 'label': 'Backup protocol memory', 'unit': 'seconds', 'kind': 'float', 'default': '600', 'minimum': 0, 'maximum': 86400, 'help': 'After a backup protocol succeeds, reuse it for the same deployment and incoming protocol for this long before probing the incoming protocol again. 0 disables the memory.'},
    {'key': 'LITELLM_MENU_CODEX_COMPACTION_CAPABILITY_TTL_SECONDS', 'category': 'Fallback', 'label': 'Compaction capability memory', 'unit': 'seconds', 'kind': 'float', 'default': '1800', 'minimum': 0, 'maximum': 86400, 'help': 'How long to remember whether a third-party Responses route can return encrypted Codex compaction. The first unverified compaction sends a tiny probe without history; an unsupported result stops before signed history is forwarded and uses Codex’s local checkpoint-summary path enabled by the LiteLLM model selection. 0 probes every compaction.'},
    {'key': 'LITELLM_MENU_WEB_SEARCH_UNSUPPORTED_TTL_SECONDS', 'category': 'Fallback', 'label': 'Web search unsupported memory', 'unit': 'seconds', 'kind': 'float', 'default': '600', 'minimum': 0, 'maximum': 86400, 'help': 'After a deployment explicitly rejects native web_search, use the local pi-web-access bridge for this long before probing native search again. Transient, network, quota, and provider-search failures do not populate this memory. 0 disables cross-request memory.'},
    {'key': 'LITELLM_MENU_DEPLOYMENT_COOLDOWN_ORDINARY_ENABLED', 'category': 'Fallback', 'label': 'Ordinary requests write cooldown', 'kind': 'bool', 'default': '1', 'help': 'Whether failed ordinary requests add failures to the shared deployment cooldown pool. Existing cooldowns are still read by every request type.'},
    {'key': 'LITELLM_MENU_DEPLOYMENT_COOLDOWN_COMPACTION_ENABLED', 'category': 'Fallback', 'label': 'Compaction requests write cooldown', 'kind': 'bool', 'default': '0', 'help': 'Whether failed structured Codex compaction requests add failures to the shared deployment cooldown pool. Disabled by default so a compaction-specific upstream failure does not cool a route for ordinary work.'},
    {'key': 'LITELLM_MENU_IMAGE_TOOL_UNSUPPORTED_TTL_SECONDS', 'category': 'Fallback', 'label': 'Image tool unsupported memory', 'unit': 'seconds', 'kind': 'float', 'default': '600', 'minimum': 0, 'maximum': 86400, 'help': 'How long a deployment is skipped after a deterministic image_generation capability rejection. Parameter errors, timeouts, policy failures, and other upstream errors do not populate this memory. 0 disables cross-request memory.'},
    {'key': 'LITELLM_MENU_PREFIX_IMAGE_PREVIEW_ENABLED', 'category': 'Fallback', 'label': 'Prefix image previews', 'kind': 'bool', 'default': '1', 'help': 'Replay oversized signed-prefix view_image outputs as deterministic previews plus local-path references instead of re-uploading the original bytes every turn. The model can re-open any original at full resolution with another view_image call; original-resolution requests keep their bytes inline inside the recent window and convert to path references beyond it when the original-path switch is on.'},
    {'key': 'LITELLM_MENU_PREFIX_IMAGE_PREVIEW_MIN_BYTES', 'category': 'Fallback', 'label': 'Prefix image preview threshold', 'unit': 'bytes', 'kind': 'int', 'default': '131072', 'minimum': 1024, 'maximum': 16777216, 'help': 'Minimum inline image size before a signed-prefix view_image output is replayed as a preview. Smaller images are forwarded unchanged.'},
    {'key': 'LITELLM_MENU_PREFIX_IMAGE_MODE', 'category': 'Fallback', 'label': 'Prefix image mode', 'kind': 'enum', 'default': 'path-recent', 'options': ['preview', 'path-recent', 'off'], 'help': 'How signed-prefix view_image outputs are replayed. preview keeps a reduced preview for every oversized output; path-recent keeps previews only for the most recent image outputs and replaces older ones with pure local-path references; off disables the rewriting entirely. The model can always re-open any original with view_image.'},
    {'key': 'LITELLM_MENU_PREFIX_IMAGE_RECENT_COUNT', 'category': 'Fallback', 'label': 'Prefix image recent count', 'unit': 'images', 'kind': 'int', 'default': '6', 'minimum': 0, 'maximum': 64, 'help': 'In path-recent mode, how many of the most recent image outputs keep inline images (previews, or original bytes for original-resolution requests); older outputs become pure path references. 0 turns every oversized output into a path reference.'},
    {'key': 'LITELLM_MENU_PREFIX_IMAGE_ORIGINAL_PATH', 'category': 'Fallback', 'label': 'Path-convert original-resolution images', 'kind': 'bool', 'default': '1', 'help': 'In path-recent mode, view_image outputs explicitly requested at original resolution also become pure local-path references once they fall out of the recent window; the most recent original-resolution outputs keep their original bytes inline. Disable to always replay explicit original-resolution requests unchanged.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_BACKEND', 'category': 'Computer Facade', 'label': 'Backend', 'kind': 'enum', 'default': 'auto', 'options': ['auto', 'mcp', 'browser', 'chrome', 'playwright', 'mock'], 'help': 'Executor backend. Explicit choices do not silently fall back to another real backend.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_MODEL', 'category': 'Computer Facade', 'label': 'Planner model', 'kind': 'string', 'default': '', 'help': 'Optional model group or route for the internal JSON planner. Empty uses the request model.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_MAX_STEPS', 'category': 'Computer Facade', 'label': 'Max steps', 'unit': 'steps', 'kind': 'int', 'default': '20', 'minimum': 1, 'maximum': 200, 'help': 'Maximum computer observation/action turns before safe failure.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_TRACE', 'category': 'Computer Facade', 'label': 'Trace', 'kind': 'bool', 'default': '0', 'help': 'Log action summaries and backend choices to route trace.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_TRACE_SCREENSHOTS', 'category': 'Computer Facade', 'label': 'Trace screenshots', 'kind': 'bool', 'default': '0', 'help': 'Privacy-sensitive: when enabled, screenshots are written locally with 0600 permissions instead of being logged inline.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_ACTION_DENYLIST', 'category': 'Computer Facade', 'label': 'Action denylist', 'kind': 'string', 'default': '', 'help': 'Comma-separated actions to block, for example click,type,drag.'},
    {'key': 'LITELLM_MENU_COMPUTER_FACADE_REQUIRE_OBSERVATION', 'category': 'Computer Facade', 'label': 'Require observation', 'kind': 'bool', 'default': '1', 'help': 'Require executor observation before planner completion or action success.'},
    {'key': 'LITELLM_MENU_MCP_AUTO_APPROVE', 'category': 'MCP', 'label': 'Auto-approve MCP tools', 'kind': 'bool', 'default': '0', 'help': 'When enabled, set Responses API MCP tools to require_approval=never so the upstream service does not pause for interactive approval. Disabled by default because it bypasses MCP safety review.'},
    {'key': 'LITELLM_MENU_LOG_MAX_BYTES', 'category': 'Logs', 'label': 'Local log file cap', 'unit': 'MB', 'kind': 'mb', 'default': '10', 'minimum': 0.25, 'maximum': 100, 'help': 'Per-file cap for local logs: recent requests, service stdout/stderr, and menu actions. Each log keeps one .1 backup containing the previous tail.'},
    {'key': 'LITELLM_MENU_LOG_VIEW_LIMIT', 'category': 'Logs', 'label': 'Log view rows', 'unit': 'rows', 'kind': 'int', 'default': '10000', 'minimum': 100, 'maximum': 100000, 'help': 'Maximum rows shown per log tab. This changes the view only and does not delete local log data.'},
    {'key': 'LITELLM_MENU_ROUTE_TRACE_PREVIEW_CHARS', 'category': 'Logs', 'label': 'Trace preview chars', 'unit': 'chars', 'kind': 'int', 'default': '2000', 'minimum': 80, 'maximum': 2000, 'help': 'Maximum request-preview characters retained in the always-on local route trace.'},
    {'key': 'LITELLM_USE_SYSTEM_PROXIES', 'category': 'Network', 'label': 'Use system proxies', 'kind': 'bool', 'default': '0', 'help': 'Allow upstream HTTP clients to use macOS system proxy settings. Off isolates LiteLLM from system proxy auto-discovery.'},
    {'key': 'LITELLM_PORT', 'category': 'Service', 'label': 'Local port', 'kind': 'int', 'default': '4000', 'minimum': 1, 'maximum': 65535, 'help': 'Local HTTP port for the LiteLLM proxy. Changing this updates health checks and requires a service restart.'},
    {'key': 'LITELLM_MENU_WEBSOCKET_MAX_FRAME_BYTES', 'category': 'Service', 'label': 'WebSocket frame limit', 'unit': 'bytes', 'kind': 'int', 'default': '67108864', 'minimum': 1048576, 'maximum': 1073741824, 'help': 'Maximum inbound WebSocket message frame accepted by the local proxy. Codex sends each Responses turn request, including the signed replay history, as one frame; a smaller limit closes it with code 1009 before routing and Codex reconnects in a loop. Requires a service restart.'},
    {'key': 'LITELLM_NUM_WORKERS', 'category': 'Service', 'label': 'Worker count', 'unit': 'workers', 'kind': 'int', 'default': '16', 'minimum': 1, 'maximum': 64, 'help': 'LiteLLM Menu runs 16 Uvicorn workers by default. Keep this value at 16 unless the user explicitly changes the service concurrency setting.'},
    {'key': 'LITELLM_MAX_REQUESTS_BEFORE_RESTART', 'category': 'Service', 'label': 'Worker request recycle', 'unit': 'requests', 'kind': 'int', 'default': '1000', 'minimum': 1, 'maximum': 100000, 'help': 'Restart each Gunicorn worker after this many handled requests to cap long-running memory growth.'},
    {'key': 'LITELLM_STATE_TTL_SECONDS', 'category': 'Service', 'label': 'State TTL', 'unit': 'seconds', 'kind': 'int', 'default': '180', 'minimum': 1, 'maximum': 3600, 'help': 'How long transient start/stop state is considered fresh.'},
    {'key': 'LITELLM_HEALTH_WAIT_SECONDS', 'category': 'Service', 'label': 'Health wait', 'unit': 'seconds', 'kind': 'int', 'default': '60', 'minimum': 1, 'maximum': 600, 'help': 'How long start/restart waits for the health endpoint.'},
    {'key': 'LITELLM_RUNTIME_VERIFY_WAIT_SECONDS', 'category': 'Service', 'label': 'Runtime verify wait', 'unit': 'seconds', 'kind': 'int', 'default': '30', 'minimum': 1, 'maximum': 600, 'help': 'How long runtime config verification may wait.'},
    {'key': 'LITELLM_SERVICE_LIFECYCLE_LOCK_WAIT_SECONDS', 'category': 'Service', 'label': 'Lifecycle lock wait', 'unit': 'seconds', 'kind': 'int', 'default': '120', 'minimum': 1, 'maximum': 1800, 'help': 'Maximum wait for concurrent start/restart/apply-config operations.'},
)


def runtime_settings_metadata() -> list[dict[str, object]]:
    """Return a defensive copy for UI projection and validation."""

    return [dict(item) for item in RUNTIME_SETTINGS_SCHEMA]
