// Generated by rn/scripts/gen-native-specs.mjs from ui/nativeSpecs/NativeSplitView.spec.ts;
// edit the source file, not this one.

import { codegenNativeComponent } from "react-native";
import type { ViewProps } from "react-native";
import type {
  DirectEventHandler,
  Float,
  WithDefault,
} from "react-native/Libraries/Types/CodegenTypes";

type PaneWidthChangeEvent = Readonly<{ width: Float }>;

export interface NativeSplitViewProps extends ViewProps {
  paneWidth: Float;
  minPaneWidth: Float;
  maxPaneWidth: Float;
  paneOpen?: WithDefault<boolean, true>;
  disabled?: WithDefault<boolean, false>;
  onPaneWidthChange?: DirectEventHandler<PaneWidthChangeEvent>;
}

export default codegenNativeComponent<NativeSplitViewProps>("LiteLLMWinUISplitView");
