// Generated by rn/scripts/gen-native-specs.mjs from ui/nativeSpecs/NativeCheckbox.spec.ts;
// edit the source file, not this one.

import { codegenNativeComponent } from "react-native";
import type { ViewProps } from "react-native";
import type {
  DirectEventHandler,
  WithDefault,
} from "react-native/Libraries/Types/CodegenTypes";

type ChangeEvent = Readonly<{ value: boolean }>;

export interface NativeCheckboxProps extends ViewProps {
  label: string;
  value?: WithDefault<boolean, false>;
  disabled?: WithDefault<boolean, false>;
  compact?: WithDefault<boolean, false>;
  labelVisible?: WithDefault<boolean, true>;
  onValueChange?: DirectEventHandler<ChangeEvent>;
}

export default codegenNativeComponent<NativeCheckboxProps>("LiteLLMWinUICheckbox");
