// Generated by rn/scripts/gen-native-specs.mjs from ui/nativeSpecs/NativeToggle.spec.ts;
// edit the source file, not this one.

import { codegenNativeComponent } from "react-native";
import type { ViewProps } from "react-native";
import type { DirectEventHandler, WithDefault } from "react-native/Libraries/Types/CodegenTypes";

type ChangeEvent = Readonly<{ value: boolean }>;

export interface NativeToggleProps extends ViewProps {
  value?: WithDefault<boolean, false>;
  disabled?: WithDefault<boolean, false>;
  onValueChange?: DirectEventHandler<ChangeEvent>;
  /**
   * The name a screen reader announces for this switch.  The control draws as
   * a bare 24pt box with an “x” glyph, so without the label every switch in
   * the settings windows reads as the same untranslated word.
   */
  accessibilityLabel?: string;
}

export default codegenNativeComponent<NativeToggleProps>("LiteLLMWinUISwitch");
